name: Manual Update Main Scoreboard

on:
  workflow_dispatch:
    inputs:
      scoreboard_type:
        description: 'Which main scoreboard to update'
        required: true
        type: choice
        options:
          - 'classic'
          - 'package'
          - 'both'
        default: 'both'

permissions:
  contents: write

concurrency:
  group: manual-update-main-scoreboard
  cancel-in-progress: false

jobs:
  update-main-scoreboard:
    runs-on: ubuntu-latest
    if: github.repository == 'RezaSi/go-interview-practice'

    steps:
      - name: Trigger Classic Main Scoreboard
        if: github.event.inputs.scoreboard_type == 'classic' || github.event.inputs.scoreboard_type == 'both'
        run: |
          echo "🏆 Triggering classic main scoreboard update..."
          
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-main-scoreboard.yml/dispatches \
            -d '{"ref":"main"}'
          
          echo "✅ Classic main scoreboard update triggered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Package Main Scoreboard
        if: github.event.inputs.scoreboard_type == 'package' || github.event.inputs.scoreboard_type == 'both'
        run: |
          echo "🚀 Triggering package main scoreboard update..."
          
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-main-package-scoreboard.yml/dispatches \
            -d '{"ref":"main"}'
          
          echo "✅ Package main scoreboard update triggered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "## 🏆 Main Scoreboard Update Triggered" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Type:** ${{ github.event.inputs.scoreboard_type }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🚀 Actions Performed" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event.inputs.scoreboard_type }}" == "classic" ]; then
            echo "- ✅ Triggered classic main scoreboard update" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ github.event.inputs.scoreboard_type }}" == "package" ]; then
            echo "- ✅ Triggered package main scoreboard update" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ✅ Triggered classic main scoreboard update" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Triggered package main scoreboard update" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ⏱️ Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "Check the Actions tab for the triggered workflows:" >> $GITHUB_STEP_SUMMARY
          echo "- 🎯 **Update Main Scoreboard** (for classic challenges)" >> $GITHUB_STEP_SUMMARY
          echo "- 📦 **Update Main Package Scoreboard** (for package challenges)" >> $GITHUB_STEP_SUMMARY 