name: Update Scoreboards

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-scoreboards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Tests and Update Scoreboards
        run: |
          for challenge_dir in challenge-*/; do
            challenge_name=$(basename "$challenge_dir")
            echo "Processing $challenge_name"

            # Ensure go.mod exists
            if [ ! -f "$challenge_dir/go.mod" ]; then
              (cd "$challenge_dir" && go mod init "$challenge_name")
            fi

            # Initialize scoreboard
            scoreboard="$challenge_dir/SCOREBOARD.md"
            echo "# Scoreboard for $challenge_name" > "$scoreboard"
            echo "| Username   | Passed Tests | Total Tests | Last Submission Time |" >> "$scoreboard"
            echo "|------------|--------------|-------------|----------------------|" >> "$scoreboard"

            # Temporary file to store scoreboard data
            temp_scoreboard=$(mktemp)

            # Run tests for all submissions
            for submission_dir in "$challenge_dir"/submissions/*/; do
              USERNAME=$(basename "$submission_dir")
              echo "Testing submission from $USERNAME"

              # Copy submission files
              cp "$submission_dir"/*.go "$challenge_dir/"

              # Run tests and capture output
              (cd "$challenge_dir" && go test -v) > "$submission_dir/test_results.txt" 2>&1 || true

              # Output test results for debugging
              echo "Test results for $USERNAME:"
              cat "$submission_dir/test_results.txt"

              # Parse test results for subtests only
              PASS_COUNT=$(grep -c "^    --- PASS: " "$submission_dir/test_results.txt" || true)
              FAIL_COUNT=$(grep -c "^    --- FAIL: " "$submission_dir/test_results.txt" || true)
              TOTAL_TESTS=$((PASS_COUNT + FAIL_COUNT))

              # Record the current time as the submission time
              SUBMISSION_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

              # Store data into the temporary scoreboard
              echo "$USERNAME,$PASS_COUNT,$TOTAL_TESTS,$SUBMISSION_TIME" >> "$temp_scoreboard"

              # Clean up copied files
              rm -f "$challenge_dir"/*.go
            done

            # Sort scoreboard data and append to SCOREBOARD.md
            awk -F',' 'BEGIN { OFS=" | "; print "| Username", "Passed Tests", "Total Tests", "Last Submission Time |"; print "|------------", "--------------", "-------------", "----------------------|"; } 
              { print "| " $1, $2, $3, $4 " |"; }' <(sort -t ',' -k2,2nr -k4,4r "$temp_scoreboard") >> "$scoreboard"

            # Remove the temporary scoreboard file
            rm "$temp_scoreboard"
          done

      - name: Commit and Push Scoreboards
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add challenge-*/SCOREBOARD.md
          git commit -m "Update scoreboards [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
