name: Update Scoreboards

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-scoreboards:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Tests and Update Scoreboards
        run: |
          for challenge_dir in challenge-*/; do
            [ -d "$challenge_dir" ] || continue
            challenge_name=$(basename "$challenge_dir")
            echo "Processing $challenge_name"

            # Ensure go.mod exists
            if [ ! -f "$challenge_dir/go.mod" ]; then
              (cd "$challenge_dir" && go mod init "$challenge_name")
            fi

            # Initialize scoreboard
            scoreboard="$challenge_dir/SCOREBOARD.md"
            echo "# Scoreboard for $challenge_name" > "$scoreboard"
            echo "| Username   | Passed Tests | Total Tests |" >> "$scoreboard"
            echo "|------------|--------------|-------------|" >> "$scoreboard"

            # Run tests for all submissions
            for submission_dir in "$challenge_dir"/submissions/*/; do
              # Skip if not a directory
              [ -d "$submission_dir" ] || continue

              USERNAME=$(basename "$submission_dir")
              echo "Testing submission from $USERNAME"

              # Copy participant's *.go files
              cp "$submission_dir"/*.go "$challenge_dir/" 2>/dev/null || true

              # Run tests and capture output
              (cd "$challenge_dir" && go test -v) > "$submission_dir/test_results.txt" 2>&1 || true

              # Show logs
              echo "Test results for $USERNAME:"
              cat "$submission_dir/test_results.txt"

              # Parse test results
              PASS_COUNT=$(grep -c "^[[:space:]]*--- PASS: " "$submission_dir/test_results.txt" || true)
              FAIL_COUNT=$(grep -c "^[[:space:]]*--- FAIL: " "$submission_dir/test_results.txt" || true)
              TOTAL_TESTS=$((PASS_COUNT + FAIL_COUNT))

              # Update scoreboard
              echo "| $USERNAME | $PASS_COUNT | $TOTAL_TESTS |" >> "$scoreboard"

              # Clean up copied participant files, keep any _test.go
              for f in "$challenge_dir"/*.go; do
                case "$f" in
                  *_test.go)
                    # Keep official test file
                    ;;
                  *.go)
                    rm -f "$f"
                    ;;
                esac
              done
            done

            # Sort scoreboard by Passed Tests desc; skip the first 3 lines (header)
            if [ -s "$scoreboard" ]; then
              temp_sorted=$(mktemp)
              head -n 3 "$scoreboard" > "$temp_sorted"
              tail -n +4 "$scoreboard" \
                | sort -t '|' -k3,3nr \
                >> "$temp_sorted"
              mv "$temp_sorted" "$scoreboard"
            fi
          done

      - name: Commit and Push Scoreboard Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add challenge-*/SCOREBOARD.md
          git commit -m "📊 Update individual challenge scoreboards

          - Updated test results for all submissions
          - Refreshed completion statistics
          - Sorted by performance" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
